"""create country

Revision ID: 0001
Revises:
Create Date: 2026-09-28 20:48:35.785777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ne_geometry_ref', sa.String(length=500), nullable=False),
    sa.Column('bbox_json', sa.JSON(), nullable=False),
    sa.Column('geofabrik_path', sa.String(length=200), nullable=False),
    sa.Column('wof_code', sa.String(length=10), nullable=False),
    sa.Column('srtm_bbox_json', sa.JSON(), nullable=False),
    sa.Column('openaddresses_files_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('iso2', name=op.f('pk_country'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    # ### end Alembic commands ###
